export const GET_INGREDIENTS_LOADING = "GET_INGREDIENTS_LOADING";
export const GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_ERROR = "GET_INGREDIENTS_ERROR";

export const SEARCH_INGREDIENTS_LOADING = "SEARCH_INGREDIENTS_LOADING";
export const SEARCH_INGREDIENTS_SUCCESS = "SEARCH_INGREDIENTS_SUCCESS";
export const SEARCH_INGREDIENTS_ERROR = "SEARCH_INGREDIENTS_ERROR";